name: .NET

on:
  push:
    branches: [ Testing ]
  pull_request:
    branches: [ Testing ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Dotnet Side by Side testing sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0'
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0'
      - name: Build 
        run: dotnet build GraphCompression
      - name: Test
        run: dotnet test GraphCompression
