name: TSK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build GraphCompression with test
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0'
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0'
      - name: Restore dependencies
        run: dotnet restore GraphCompression
      - name: Build 
        run: dotnet build GraphCompression
      - name: Test
        run: dotnet test GraphCompression