name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Dotnet Side by Side testing sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0'
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0'
      - name: Restore dependencies
        run: dotnet restore GraphCompression
      - name: Build 
        run: dotnet build
        working-directory: src/GraphCompression 
      - name: Test
        run: dotnet test
        working-directory: src/GraphCompression 
